/**
 * Tests for Claude Conversations Filters
 *
 * Verifies message filtering logic for conversation sync
 */

import { describe, it, expect } from 'vitest';
import {
  isToolResult,
  isSystemMessage,
  isConversationSplitter,
  shouldFilterMessage
} from '../claude.conversations-filters.js';
import type { ClaudeMessage } from '../claude.conversations-types.js';

describe('Claude Conversations Filters', () => {
  describe('isToolResult', () => {
    it('should filter messages with ONLY tool_result content', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-1',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: [
            {
              type: 'tool_result',
              content: 'Tool output here',
              tool_use_id: 'tool-123'
            }
          ]
        }
      };

      expect(isToolResult(msg)).toBe(true);
    });

    it('should NOT filter messages with both text and tool_result', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-2',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: [
            {
              type: 'text',
              text: 'User message with rejection'
            },
            {
              type: 'tool_result',
              content: '<tool_use_error>File does not exist.</tool_use_error>',
              is_error: true,
              tool_use_id: 'tool-456'
            }
          ]
        }
      };

      expect(isToolResult(msg)).toBe(false);
    });

    it('should NOT filter messages with only text content', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-3',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: [
            {
              type: 'text',
              text: 'Regular user message'
            }
          ]
        }
      };

      expect(isToolResult(msg)).toBe(false);
    });

    it('should NOT filter messages with empty/whitespace text and tool_result', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-4',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: [
            {
              type: 'text',
              text: '   '  // Only whitespace
            },
            {
              type: 'tool_result',
              content: 'Tool output',
              tool_use_id: 'tool-789'
            }
          ]
        }
      };

      // Empty/whitespace text should be treated as no text
      expect(isToolResult(msg)).toBe(true);
    });

    it('should NOT filter assistant messages', () => {
      const msg: ClaudeMessage = {
        type: 'assistant',
        uuid: 'test-5',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: [
            {
              type: 'tool_result',
              content: 'Tool output',
              tool_use_id: 'tool-999'
            }
          ]
        }
      };

      expect(isToolResult(msg)).toBe(false);
    });
  });

  describe('isSystemMessage', () => {
    it('should filter caveat warnings', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-6',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: 'Caveat: The messages below were generated by the user while running local commands'
        }
      };

      expect(isSystemMessage(msg)).toBe(true);
    });

    it('should filter /compact commands', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-7',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: '<command-name>/compact</command-name>'
        }
      };

      expect(isSystemMessage(msg)).toBe(true);
    });

    it('should filter /compress commands', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-8',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: '<command-name>/compress</command-name>'
        }
      };

      expect(isSystemMessage(msg)).toBe(true);
    });

    it('should NOT filter regular user messages', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-9',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: 'Fix the bug in the code'
        }
      };

      expect(isSystemMessage(msg)).toBe(false);
    });
  });

  describe('isConversationSplitter', () => {
    it('should detect /clear command', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-10',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: '<command-name>/clear</command-name>'
        }
      };

      expect(isConversationSplitter(msg)).toBe(true);
    });

    it('should NOT detect /compact as conversation splitter', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-11',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: '<command-name>/compact</command-name>'
        }
      };

      expect(isConversationSplitter(msg)).toBe(false);
    });
  });

  describe('shouldFilterMessage', () => {
    it('should filter conversation splitters', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-12',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: '<command-name>/clear</command-name>'
        }
      };

      expect(shouldFilterMessage(msg)).toBe(true);
    });

    it('should filter system messages', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-13',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: '<command-name>/compact</command-name>'
        }
      };

      expect(shouldFilterMessage(msg)).toBe(true);
    });

    it('should filter tool-result-only messages', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-14',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: [
            {
              type: 'tool_result',
              content: 'Tool output',
              tool_use_id: 'tool-123'
            }
          ]
        }
      };

      expect(shouldFilterMessage(msg)).toBe(true);
    });

    it('should NOT filter regular user messages', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-15',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: 'Help me fix this bug'
        }
      };

      expect(shouldFilterMessage(msg)).toBe(false);
    });

    it('should NOT filter messages with text + tool_result (BUG FIX)', () => {
      const msg: ClaudeMessage = {
        type: 'user',
        uuid: 'test-16',
        timestamp: '2026-01-09T10:00:00Z',
        message: {
          content: [
            {
              type: 'text',
              text: 'still not done. session synced but "Core infrastructure is solid."'
            },
            {
              type: 'tool_result',
              content: '<tool_use_error>File does not exist.</tool_use_error>',
              is_error: true,
              tool_use_id: 'toolu_bdrk_01XBLdGrjL9b4tpWFcmyefwK'
            }
          ]
        }
      };

      // This is the bug fix: messages with both text and tool_result should NOT be filtered
      expect(shouldFilterMessage(msg)).toBe(false);
    });
  });
});
