import { readFile, writeFile, mkdir, chmod, rm } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { getDirname, resolveHomeDir } from '@/utils/paths.js';
import { logger } from '@/utils/logger.js';
import { sanitizeLogArgs } from '@/utils/security.js';
import { ConfigurationError } from '@/utils/errors.js';

export const STATUSLINE_NAME = 'statusline';
export const STATUSLINE_DISPLAY_NAME = 'CodeMie Statusline';
export const STATUSLINE_DESCRIPTION = 'Budget usage, project, branch, model, context & token stats for Claude Code';

const SCRIPT_FILENAME = 'codemie-budget-status.js';
const LEGACY_SCRIPT_FILENAME = 'codemie-statusline.mjs';
const REFRESH_INTERVAL = 60;

export interface InstallStatuslineResult {
  scriptPath: string;
  alreadyConfigured: boolean;
}

const TRANSCRIPT_COST_IMPORT_MARKER = '/* __CODEMIE_TRANSCRIPT_COST_IMPORT__ */';

function escapeRegExp(literal: string): string {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Build the deployed statusline as one self-contained file, inlining `transcript-cost.mjs`
 * into `statusline.mjs`. The script runs as `node <path>` from ~/.claude after this process
 * exits, so it cannot import from the package.
 *
 * @throws ConfigurationError when statusline.mjs has lost its substitution marker.
 */
async function buildStatuslineScript(): Promise<string> {
  const pluginDir = join(getDirname(import.meta.url), 'plugin');
  const [statusline, transcriptCost] = await Promise.all([
    readFile(join(pluginDir, 'statusline.mjs'), 'utf-8'),
    readFile(join(pluginDir, 'transcript-cost.mjs'), 'utf-8'),
  ]);

  if (!statusline.includes(TRANSCRIPT_COST_IMPORT_MARKER)) {
    throw new ConfigurationError(
      `Statusline source statusline.mjs is missing its ${TRANSCRIPT_COST_IMPORT_MARKER} marker`
    );
  }

  // Inlining flattens the module into statusline.mjs's scope, so an import here would be
  // dropped and surface only as a ReferenceError in the deployed copy.
  if (/^import\s/m.test(transcriptCost)) {
    throw new ConfigurationError(
      'Statusline source transcript-cost.mjs must have no imports; it is inlined into the deployed script'
    );
  }

  const inlinedCost = transcriptCost.replace(/^export /gm, '');

  const body = statusline.replace(
    new RegExp(`${escapeRegExp(TRANSCRIPT_COST_IMPORT_MARKER)}\\n?import[^\\n]*'\\./transcript-cost\\.mjs';`),
    ''
  );

  const lines = body.split('\n');
  const shebang = lines[0].startsWith('#!') ? `${lines.shift()}\n` : '';
  return `${shebang}// GENERATED by codemie install statusline — do not edit. Source: plugin/statusline.mjs\n${inlinedCost}\n${lines.join('\n')}`;
}

export async function installStatusline(): Promise<InstallStatuslineResult> {
  const claudeHome = resolveHomeDir('.claude');
  const scriptPath = join(claudeHome, SCRIPT_FILENAME);
  const settingsPath = join(claudeHome, 'settings.json');

  const scriptContent = await buildStatuslineScript();

  if (!existsSync(claudeHome)) {
    await mkdir(claudeHome, { recursive: true });
  }

  await writeFile(scriptPath, scriptContent, 'utf-8');
  if (process.platform !== 'win32') {
    await chmod(scriptPath, 0o755);
  }

  let settings: Record<string, unknown> = {};
  if (existsSync(settingsPath)) {
    try {
      const raw = await readFile(settingsPath, 'utf-8');
      settings = JSON.parse(raw) as Record<string, unknown>;
    } catch (parseError) {
      logger.warn(
        '[Statusline] Could not parse settings.json, aborting to avoid data loss',
        ...sanitizeLogArgs({ settingsPath, error: parseError instanceof Error ? parseError.message : String(parseError) })
      );
      throw new ConfigurationError('Could not parse ~/.claude/settings.json');
    }
  }

  const alreadyConfigured = Boolean(settings.statusLine);

  settings.statusLine = {
    type: 'command',
    command: `node "${scriptPath}"`,
    refreshInterval: REFRESH_INTERVAL,
  };

  await writeFile(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
  logger.debug('[Statusline] Installed', ...sanitizeLogArgs({ scriptPath }));
  return { scriptPath, alreadyConfigured };
}

export async function uninstallStatusline(): Promise<void> {
  const claudeHome = resolveHomeDir('.claude');
  const scriptPath = join(claudeHome, SCRIPT_FILENAME);
  const legacyScriptPath = join(claudeHome, LEGACY_SCRIPT_FILENAME);
  const settingsPath = join(claudeHome, 'settings.json');

  if (existsSync(scriptPath)) {
    await rm(scriptPath);
  }
  // Clean up the orphaned artifact from the old, now-removed --status flag mechanism,
  // in case it was ever written by a version prior to this consolidation.
  if (existsSync(legacyScriptPath)) {
    await rm(legacyScriptPath);
  }

  if (existsSync(settingsPath)) {
    try {
      const raw = await readFile(settingsPath, 'utf-8');
      const settings = JSON.parse(raw) as Record<string, unknown>;
      if (settings.statusLine) {
        delete settings.statusLine;
        await writeFile(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
      }
    } catch (parseError) {
      logger.warn(
        '[Statusline] Could not parse settings.json during uninstall',
        ...sanitizeLogArgs({ settingsPath, error: parseError instanceof Error ? parseError.message : String(parseError) })
      );
      throw new ConfigurationError('Could not parse ~/.claude/settings.json');
    }
  }

  logger.debug('[Statusline] Uninstalled');
}

export function isStatuslineInstalled(): boolean {
  return existsSync(join(homedir(), '.claude', SCRIPT_FILENAME));
}
